import type { Metadata } from "next";
import "./globals.css";
import { Poppins as FontSans } from "next/font/google";
import { Chakra_Petch } from "next/font/google";
import { Archivo } from "next/font/google";
import { Providers } from "./providers";
import { Header } from "@/components/Header";

const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});
const fontChakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-chakra",
});
const fontArchivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-Archivo",
});
export const metadata: Metadata = {
  title: "Home",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${fontSans.variable} ${fontChakra.variable} ${fontArchivo.variable}`}
      >
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
