"use client";

import type { Metadata } from "next";
import "./globals.css";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { WagmiProvider } from "wagmi";
import { config } from "./config/config";
import Header from "../components/Header";
import { Poppins as FontSans } from "next/font/google";
import { Chakra_Petch } from "next/font/google";
import { Archivo } from 'next/font/google'
const queryClient = new QueryClient();


const fontSans = FontSans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-sans",
});
const fontChakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-chakra",
});
const fontArchivo = Archivo({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-Archivo",
});
// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fontSans.variable} ${fontChakra.variable} ${fontArchivo.variable}`}>
        <WagmiProvider config={config}>
          <QueryClientProvider client={queryClient}>
              <Header />
              {children}
          </QueryClientProvider>
        </WagmiProvider>
      </body>
    </html>
  );
}
