export const coreDistributorAbi = [
  {
    inputs: [
      { name: "_name", internalType: "string", type: "string" },
      { name: "_symbol", internalType: "string", type: "string" },
      { name: "_minGasToTransfer", internalType: "uint256", type: "uint256" },
      { name: "_lzEndpoint", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "owner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "approved",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "Approval",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "owner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "operator",
        internalType: "address",
        type: "address",
      },
      { indexed: false, name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "ApprovalForAll",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_fromTokenId",
        internalType: "uint256",
        type: "uint256",
      },
      {
        indexed: false,
        name: "_toTokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "BatchMetadataUpdate",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_hashedPayload",
        internalType: "bytes32",
        type: "bytes32",
      },
    ],
    name: "CreditCleared",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_hashedPayload",
        internalType: "bytes32",
        type: "bytes32",
      },
      {
        indexed: false,
        name: "_payload",
        internalType: "bytes",
        type: "bytes",
      },
    ],
    name: "CreditStored",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_srcChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: false,
        name: "_srcAddress",
        internalType: "bytes",
        type: "bytes",
      },
      {
        indexed: false,
        name: "_nonce",
        internalType: "uint64",
        type: "uint64",
      },
      {
        indexed: false,
        name: "_payload",
        internalType: "bytes",
        type: "bytes",
      },
      { indexed: false, name: "_reason", internalType: "bytes", type: "bytes" },
    ],
    name: "MessageFailed",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_tokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "MetadataUpdate",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "previousOwner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "newOwner",
        internalType: "address",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "_srcChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: true,
        name: "_srcAddress",
        internalType: "bytes",
        type: "bytes",
      },
      {
        indexed: true,
        name: "_toAddress",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "_tokenIds",
        internalType: "uint256[]",
        type: "uint256[]",
      },
    ],
    name: "ReceiveFromChain",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_srcChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: false,
        name: "_srcAddress",
        internalType: "bytes",
        type: "bytes",
      },
      {
        indexed: false,
        name: "_nonce",
        internalType: "uint64",
        type: "uint64",
      },
      {
        indexed: false,
        name: "_payloadHash",
        internalType: "bytes32",
        type: "bytes32",
      },
    ],
    name: "RetryMessageSuccess",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "_dstChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: true,
        name: "_from",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "_toAddress",
        internalType: "bytes",
        type: "bytes",
      },
      {
        indexed: false,
        name: "_tokenIds",
        internalType: "uint256[]",
        type: "uint256[]",
      },
    ],
    name: "SendToChain",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_dstChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: false,
        name: "_dstChainIdToBatchLimit",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "SetDstChainIdToBatchLimit",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_dstChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: false,
        name: "_dstChainIdToTransferGas",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "SetDstChainIdToTransferGas",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_dstChainId",
        internalType: "uint16",
        type: "uint16",
      },
      { indexed: false, name: "_type", internalType: "uint16", type: "uint16" },
      {
        indexed: false,
        name: "_minDstGas",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "SetMinDstGas",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_minGasToTransferAndStore",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "SetMinGasToTransferAndStore",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "precrime",
        internalType: "address",
        type: "address",
      },
    ],
    name: "SetPrecrime",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_remoteChainId",
        internalType: "uint16",
        type: "uint16",
      },
      { indexed: false, name: "_path", internalType: "bytes", type: "bytes" },
    ],
    name: "SetTrustedRemote",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_remoteChainId",
        internalType: "uint16",
        type: "uint16",
      },
      {
        indexed: false,
        name: "_remoteAddress",
        internalType: "bytes",
        type: "bytes",
      },
    ],
    name: "SetTrustedRemoteAddress",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      { indexed: true, name: "from", internalType: "address", type: "address" },
      { indexed: true, name: "to", internalType: "address", type: "address" },
      {
        indexed: true,
        name: "tokenId",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "Transfer",
    anonymous: false,
    type: "event",
  },
  {
    outputs: [],
    inputs: [
      { name: "_newModerator", internalType: "address", type: "address" },
    ],
    name: "AddModerator",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "DEFAULT_PAYLOAD_SIZE_LIMIT",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    inputs: [],
    name: "FUNCTION_TYPE_SEND",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_isMaintaining", internalType: "bool", type: "bool" }],
    name: "UpdateMaintaining",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [],
    name: "_baseTokenURI",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "approve",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "owner", internalType: "address", type: "address" }],
    name: "balanceOf",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_payload", internalType: "bytes", type: "bytes" }],
    name: "clearCredits",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "depositFund",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    name: "dstChainIdToBatchLimit",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    name: "dstChainIdToTransferGas",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "nativeFee", internalType: "uint256", type: "uint256" },
      { name: "zroFee", internalType: "uint256", type: "uint256" },
    ],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_toAddress", internalType: "bytes", type: "bytes" },
      { name: "_tokenIds", internalType: "uint256[]", type: "uint256[]" },
      { name: "_useZro", internalType: "bool", type: "bool" },
      { name: "_adapterParams", internalType: "bytes", type: "bytes" },
    ],
    name: "estimateSendBatchFee",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      { name: "nativeFee", internalType: "uint256", type: "uint256" },
      { name: "zroFee", internalType: "uint256", type: "uint256" },
    ],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_toAddress", internalType: "bytes", type: "bytes" },
      { name: "_tokenId", internalType: "uint256", type: "uint256" },
      { name: "_useZro", internalType: "bool", type: "bool" },
      { name: "_adapterParams", internalType: "bytes", type: "bytes" },
    ],
    name: "estimateSendFee",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    inputs: [
      { name: "", internalType: "uint16", type: "uint16" },
      { name: "", internalType: "bytes", type: "bytes" },
      { name: "", internalType: "uint64", type: "uint64" },
    ],
    name: "failedMessages",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_srcChainId", internalType: "uint16", type: "uint16" },
      { name: "_srcAddress", internalType: "bytes", type: "bytes" },
    ],
    name: "forceResumeReceive",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "getApproved",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    inputs: [
      { name: "_version", internalType: "uint16", type: "uint16" },
      { name: "_chainId", internalType: "uint16", type: "uint16" },
      { name: "", internalType: "address", type: "address" },
      { name: "_configType", internalType: "uint256", type: "uint256" },
    ],
    name: "getConfig",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    inputs: [
      { name: "_remoteChainId", internalType: "uint16", type: "uint16" },
    ],
    name: "getTrustedRemoteAddress",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [
      { name: "owner", internalType: "address", type: "address" },
      { name: "operator", internalType: "address", type: "address" },
    ],
    name: "isApprovedForAll",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [],
    name: "isMaintaining",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [
      { name: "_srcChainId", internalType: "uint16", type: "uint16" },
      { name: "_srcAddress", internalType: "bytes", type: "bytes" },
    ],
    name: "isTrustedRemote",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [
      {
        name: "",
        internalType: "contract ILayerZeroEndpoint",
        type: "address",
      },
    ],
    inputs: [],
    name: "lzEndpoint",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_srcChainId", internalType: "uint16", type: "uint16" },
      { name: "_srcAddress", internalType: "bytes", type: "bytes" },
      { name: "_nonce", internalType: "uint64", type: "uint64" },
      { name: "_payload", internalType: "bytes", type: "bytes" },
    ],
    name: "lzReceive",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [
      { name: "", internalType: "uint16", type: "uint16" },
      { name: "", internalType: "uint16", type: "uint16" },
    ],
    name: "minDstGasLookup",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "minGasToTransferAndStore",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [
      { name: "_owner", internalType: "address", type: "address" },
      { name: "_tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "mintNextToken",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "moderators",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [],
    name: "name",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_srcChainId", internalType: "uint16", type: "uint16" },
      { name: "_srcAddress", internalType: "bytes", type: "bytes" },
      { name: "_nonce", internalType: "uint64", type: "uint64" },
      { name: "_payload", internalType: "bytes", type: "bytes" },
    ],
    name: "nonblockingLzReceive",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "owner",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "ownerOf",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    name: "payloadSizeLimitLookup",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "precrime",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_srcChainId", internalType: "uint16", type: "uint16" },
      { name: "_srcAddress", internalType: "bytes", type: "bytes" },
      { name: "_nonce", internalType: "uint64", type: "uint64" },
      { name: "_payload", internalType: "bytes", type: "bytes" },
    ],
    name: "retryMessage",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "safeTransferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
      { name: "data", internalType: "bytes", type: "bytes" },
    ],
    name: "safeTransferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_from", internalType: "address", type: "address" },
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_toAddress", internalType: "bytes", type: "bytes" },
      { name: "_tokenIds", internalType: "uint256[]", type: "uint256[]" },
      {
        name: "_refundAddress",
        internalType: "address payable",
        type: "address",
      },
      { name: "_zroPaymentAddress", internalType: "address", type: "address" },
      { name: "_adapterParams", internalType: "bytes", type: "bytes" },
    ],
    name: "sendBatchFrom",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_from", internalType: "address", type: "address" },
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_toAddress", internalType: "bytes", type: "bytes" },
      { name: "_tokenId", internalType: "uint256", type: "uint256" },
      {
        name: "_refundAddress",
        internalType: "address payable",
        type: "address",
      },
      { name: "_zroPaymentAddress", internalType: "address", type: "address" },
      { name: "_adapterParams", internalType: "bytes", type: "bytes" },
    ],
    name: "sendFrom",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "operator", internalType: "address", type: "address" },
      { name: "approved", internalType: "bool", type: "bool" },
    ],
    name: "setApprovalForAll",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "baseURI", internalType: "string", type: "string" }],
    name: "setBaseURI",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_version", internalType: "uint16", type: "uint16" },
      { name: "_chainId", internalType: "uint16", type: "uint16" },
      { name: "_configType", internalType: "uint256", type: "uint256" },
      { name: "_config", internalType: "bytes", type: "bytes" },
    ],
    name: "setConfig",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      {
        name: "_dstChainIdToBatchLimit",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "setDstChainIdToBatchLimit",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      {
        name: "_dstChainIdToTransferGas",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "setDstChainIdToTransferGas",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_newCap", internalType: "uint256", type: "uint256" }],
    name: "setMaxCap",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_packetType", internalType: "uint16", type: "uint16" },
      { name: "_minGas", internalType: "uint256", type: "uint256" },
    ],
    name: "setMinDstGas",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "_minGasToTransferAndStore",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "setMinGasToTransferAndStore",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_dstChainId", internalType: "uint16", type: "uint16" },
      { name: "_size", internalType: "uint256", type: "uint256" },
    ],
    name: "setPayloadSizeLimit",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_precrime", internalType: "address", type: "address" }],
    name: "setPrecrime",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_version", internalType: "uint16", type: "uint16" }],
    name: "setReceiveVersion",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_version", internalType: "uint16", type: "uint16" }],
    name: "setSendVersion",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_remoteChainId", internalType: "uint16", type: "uint16" },
      { name: "_path", internalType: "bytes", type: "bytes" },
    ],
    name: "setTrustedRemote",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "_remoteChainId", internalType: "uint16", type: "uint16" },
      { name: "_remoteAddress", internalType: "bytes", type: "bytes" },
    ],
    name: "setTrustedRemoteAddress",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [
      { name: "srcChainId", internalType: "uint16", type: "uint16" },
      { name: "toAddress", internalType: "address", type: "address" },
      { name: "index", internalType: "uint256", type: "uint256" },
      { name: "creditsRemain", internalType: "bool", type: "bool" },
    ],
    inputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    name: "storedCredits",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "interfaceId", internalType: "bytes4", type: "bytes4" }],
    name: "supportsInterface",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [],
    name: "symbol",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "tokenDeposits",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "string", type: "string" }],
    inputs: [{ name: "tokenId", internalType: "uint256", type: "uint256" }],
    name: "tokenURI",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [
      { name: "", internalType: "uint256", type: "uint256" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "tokenWorshippers",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    name: "tokenWorshippersCount",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    inputs: [],
    name: "totalModerators",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "totalTokenDeposit",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      { name: "from", internalType: "address", type: "address" },
      { name: "to", internalType: "address", type: "address" },
      { name: "tokenId", internalType: "uint256", type: "uint256" },
    ],
    name: "transferFrom",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bytes", type: "bytes" }],
    inputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    name: "trustedRemoteLookup",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [
      { name: "", internalType: "address", type: "address" },
      { name: "", internalType: "uint256", type: "uint256" },
    ],
    name: "userWorshipCount",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "withdrawAll",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_amount", internalType: "uint256", type: "uint256" }],
    name: "withdrawTokenDeposit",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_tokenId", internalType: "uint256", type: "uint256" }],
    name: "worshipToken",
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
