export const coreMintAbi = [
  {
    inputs: [
      {
        name: "_blockchainSuperheroes",
        internalType: "address",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    inputs: [
      {
        indexed: false,
        name: "_owner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: false,
        name: "token",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "Mint",
    anonymous: false,
    type: "event",
  },
  {
    inputs: [
      {
        indexed: true,
        name: "previousOwner",
        internalType: "address",
        type: "address",
      },
      {
        indexed: true,
        name: "newOwner",
        internalType: "address",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    anonymous: false,
    type: "event",
  },
  { stateMutability: "payable", type: "fallback" },
  {
    outputs: [],
    inputs: [
      { name: "_newModerator", internalType: "address", type: "address" },
    ],
    name: "AddModerator",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_isMaintaining", internalType: "bool", type: "bool" }],
    name: "UpdateMaintaining",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [],
    name: "_mintingPaused",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "blockchainSuperheroes",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [{ name: "_owner", internalType: "address", type: "address" }],
    name: "getBalance",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [],
    name: "isMaintaining",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [],
    name: "mint",
    stateMutability: "payable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "mintingCap",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "mintingCount",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "moderators",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "address", type: "address" }],
    inputs: [],
    name: "owner",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "renounceOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [
      {
        name: "_blockchainSuperheroes",
        internalType: "address",
        type: "address",
      },
    ],
    name: "setContract",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_mintingCap", internalType: "uint256", type: "uint256" }],
    name: "setMintingCap",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_pause", internalType: "bool", type: "bool" }],
    name: "togglePause",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    inputs: [],
    name: "tokenPrice",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [{ name: "", internalType: "uint16", type: "uint16" }],
    inputs: [],
    name: "totalModerators",
    stateMutability: "view",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "newOwner", internalType: "address", type: "address" }],
    name: "transferOwnership",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [{ name: "_newPrice", internalType: "uint256", type: "uint256" }],
    name: "updatePrice",
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    outputs: [],
    inputs: [],
    name: "withdraw",
    stateMutability: "nonpayable",
    type: "function",
  },
  { stateMutability: "payable", type: "receive" },
] as const;
